services:
  - type: web
    name: fasrec-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: R2_PUBLIC_URL
        sync: false
    plan: free
    healthCheckPath: /
